spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/v1/orders/**
        - id: payments-service
          uri: http://payments-service:8080
          predicates:
            - Path=/api/v1/payments/**

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*" 